"""
Utility modules for UI automation.
"""
from .ui_control import (
    click,
    double_click,
    right_click,
    click_and_type,
    type_text,
    press_key,
    hotkey,
    wait,
    wait_for,
    wait_for_pixel_change,
    wait_for_element_ready,
    wait_for_clipboard_change,
    is_visible,
    locate_on_screen,
    click_image,
    get_clipboard,
    set_clipboard,
    scroll,
    move_mouse,
    get_mouse_position,
    find_text_on_screen,
    wait_for_text,
    wait_till_visible,
    find_text_location,
    click_text,
    close_window,
    wait_till_save_dialog,
    enter_save_file_name,
    save_file,
    retrieve_file,
    install_pytesseract,
)
from .app_manager import connect_or_start, bring_up_window, get_window_state, find_and_close_error_dialog

__all__ = [
    # UI Control
    'click',
    'double_click',
    'right_click',
    'click_and_type',
    'type_text',
    'press_key',
    'hotkey',
    'wait',
    'wait_for',
    'wait_for_pixel_change',
    'wait_for_element_ready',
    'wait_for_clipboard_change',
    'is_visible',
    'locate_on_screen',
    'click_image',
    'get_clipboard',
    'set_clipboard',
    'scroll',
    'move_mouse',
    'get_mouse_position',
    # Text Detection
    'find_text_on_screen',
    'wait_for_text',
    'wait_till_visible',
    'find_text_location',
    'click_text',
    # Window & File Operations
    'close_window',
    'wait_till_save_dialog',
    'enter_save_file_name',
    'save_file',
    'retrieve_file',
    # Installation
    'install_pytesseract',
    # App Manager
    'connect_or_start',
    'bring_up_window',
    'get_window_state',
    'find_and_close_error_dialog',
]

